Finished desktop version
Boku52500/Portfolio pull request #5
Opened 2022-09-30 17:11 UTC by Boku52500

- Added media in css to adjust sizings.
- Added new pictures to match the screen.
- Resized everything for desktop version.
- Fixed Cards.
- Fixed linters.

2022-09-30 18:39 UTC, Felix45 requested changes
Hi @Boku52500 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

You've done well :clap: :clap: , just a few changes and your design will be good to go.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights :heavy_check_mark: 
- [ ] Passing linter checks :clap: 
- [ ] Professional readme file


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 18:39 UTC, Felix45 commented on style.css
> +@media only screen and (min-width: 768px) {
Please note that at screen widths greater than `1200px` your design is not consistent with the Figma template. The alignment of the project cards appears to be distorted. For screen sizes above `768px,` your layout needs to be responsive and consistent with the Figma template. Kindly see the screenshots below and amend this.

## Figma template
<img src="https://user-images.githubusercontent.com/16392046/193333513-a3552d2a-3a0c-4488-8fee-d76c089926b0.png" />


<img src="https://user-images.githubusercontent.com/16392046/193332760-230db1d7-ed48-4e20-bee6-d56b1cf0a5cf.png" />

## Your Implementation at 1200px

<img src="https://user-images.githubusercontent.com/16392046/193332172-e3e6f09d-13fa-40b8-a360-0f8faef3eec4.png"  />


<img src="https://user-images.githubusercontent.com/16392046/193332349-e7e41f55-59c2-480f-88ce-68b8847d92a3.png" />

## Your Implementation at 1400px
<img src="https://user-images.githubusercontent.com/16392046/193334546-38d15915-e7de-47a0-b3e2-b11d8e259dd0.png" />

2022-09-30 22:25 UTC, Boku52500 commented
- Fixed responsive resolution for 1024px
- Fixed responsive resolution for 768px
- Fixed responsive resolution for 1440px

2022-09-30 22:49 UTC, sajid-munawar requested changes
Hi @Boku52500 , 

_Great job so far 👏 💯 👍. You've done well implementing some of the requested changes. However, there are still some which aren't addressed yet. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 
  - Addressed some of the issues raised from the previous review. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
  
  - N/A 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-30 22:49 UTC, sajid-munawar commented on index.html
> -        </section>
- [ ] As the previous reviewer mention please follow figma template to match your design. kindly add an overall background color to your portfolio and give separate background color for every card and also give it a `border-radius`
## Your design👇
![card](https://user-images.githubusercontent.com/66992901/193365725-fee28278-f99d-48d7-9120-5042f2f65e3f.PNG)
 ## Figma template👇
![cardfigma](https://user-images.githubusercontent.com/66992901/193365750-5f07e74a-05f0-4006-be86-8e08f8c85571.PNG)

2022-09-30 22:49 UTC, sajid-munawar commented on style.css
> +  }
- [ ] Please remove the gap and make it like the figma template. after fixing this your card will look much more better.
## your design👇
![getbtn](https://user-images.githubusercontent.com/66992901/193366248-0d7eaf50-267a-484b-962a-7eb2dbfb42ed.PNG)

## Figma design 👇
![getbtnFigma](https://user-images.githubusercontent.com/66992901/193366276-e11dcf88-f361-4c1d-93ed-ebed5283a01a.PNG)

2022-10-01 23:28 UTC, Boku52500 commented
- Reconstructed the whole design from scratch
- Updated the designs for cards for all versions
- Fixed margins for all versions
- Fixed linters

2022-10-01 23:36 UTC, mgmediaweb approved these changes
Hi @Boku52500, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved5](https://user-images.githubusercontent.com/41912912/193431986-c9f0de0d-9c70-46aa-bb33-83e50c5f06b4.gif)

## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-01 23:56 UTC, merged